gems:
    image: ubuntu:15.04
    volumes:
        - /opt/gem

web:
    image: cliffom/rails
    environment:
        - GEM_HOME=/opt/gem
    volumes:
        - .:/app
    volumes_from:
        - gems
    ports:
        - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0